---
_dataset_:
  title: "     ATP Tour"
  comment: >
    Here is a list of the best tennis players in the ATP rankings
    from 2012 to 2022, as well as the list of winners of the
    4 major Grand Slam tournaments.
  metadatas:
    sources:
      - https://github.com/JeffSackmann/tennis_atp
    font: doom
    removetitlelines: 2
tables:
  players:
    tablename: players
    subtitle: The best players (number of winning matches) beetween 2012-2022
    comment: ""
    columns:
      - winner_ioc
      - name_first
      - name_last
      - hand
      - height
      - birth
      - nbwins
    metadatas:
      aligns:
        - left
        - right
        - left
        - center
        - right
        - right
        - right
      sources: https://github.com/JeffSackmann/tennis_atp
  australian_open:
    tablename: australian_open
    subtitle: Australian Open winners beetween 2012-2022
    comment: >
      The Australian Open is a tennis tournament held annually at Melbourne Park
      in Melbourne, Victoria, Australia. The tournament is the first of the
      four Grand Slam tennis events held each year.
    columns:
      - year
      - tourney name
      - birth nat
      - winner
    metadatas:
      aligns:
        - right
        - left
        - center
        - center
      sources:
        - https://fr.wikipedia.org/wiki/Open_d%27Australie
        - https://github.com/JeffSackmann/tennis_atp
  roland_garros:
    tablename: roland_garros
    subtitle: Roland Garros winners beetween 2012-2022
    comment: >
      The major tennis tournament held over two weeks at the Stade Roland Garros
      in Paris, France, beginning in late May each year.
      The tournament and venue are named after the French aviator
      Roland Garros The French Open is the premier clay court championship
      in the world and the only Grand Slam tournament currently held
      on this surface.
    columns:
      - year
      - tourney name
      - birth nat
      - winner
    metadatas:
      aligns:
        - right
        - left
        - center
        - center
      sources:
        - https://fr.wikipedia.org/wiki/Internationaux_de_France_de_tennis
        - https://github.com/JeffSackmann/tennis_atp
  us_open:
    tablename: us_open
    subtitle: US Open winners beetween 2012-2022
    comment: >
      The US Open Tennis Championships, commonly called the US Open,
      is a hardcourt tennis tournament held annually in Queens,
      New York. Since 1987, the US Open has been

      chronologically the fourth and final Grand Slam tournament of the year.
    columns:
      - year
      - tourney name
      - birth nat
      - winner
    metadatas:
      aligns:
        - right
        - left
        - center
        - center
      sources:
        - https://fr.wikipedia.org/wiki/US_Open_de_tennis
        - https://github.com/JeffSackmann/tennis_atp
  wimbledon:
    tablename: wimbledon
    subtitle: wimbledon winners beetween 2012-2022
    comment: >
      The Championships, commonly known simply as Wimbledon,
      is the oldest tennis tournament in the world and is regarded
      by many as the most prestigious. It has been held at the
      All England Lawn Tennis and Croquet Club in Wimbledon, London, since 1877
    columns:
      - year
      - tourney name
      - birth nat
      - winner
    metadatas:
      aligns:
        - right
        - left
        - center
        - center
      sources:
        - https://fr.wikipedia.org/wiki/Tournoi_de_Wimbledon
        - https://github.com/JeffSackmann/tennis_atp
generatedtitle: []
maxwidthtitle: 0
