---
name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check_requirements:
    runs-on: ubuntu-latest
    name: Check CI requirements
    steps:
      - name: check requirements
        run: |
          test -n "${{ secrets.CODECOV_TOKEN }}" || (echo "Please define CODECOV_TOKEN into github repo setting"; exit 1)

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v3

      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.14.0

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.0

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: just lint

      - name: coverage
        run: just coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./.coverage/cov.lcov

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno:
          - v1.x
          - canary
        os:
          - ubuntu-22.04
          - windows-2022
          - macOS-12
    steps:
      - uses: actions/checkout@main

      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.14.0

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.0

      - name: coverage
        run: just coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./.coverage/cov.lcov
